version: 2.1
jobs:
  build:
    description: our build and deploy job for the website
    docker:
      - image: node:boron
    steps:
      - checkout
      - run:
         name: Install awscli
         command: |
            apt-get -y -qq update
            apt-get -y -qq install awscli
            echo '*****AWS-CLI INSTALLED SUCCESSFULLY*****'
      - run: 
          name: Build the codebase
          command: ./scripts/build.sh
      - run: 
          name: Deploying the codebase'
          command: ./scripts/deploy-to-s3.sh

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: staging
