version: 2.1
jobs:
  build:
    description: our build and deploy job for the website
    docker:
      - image: node:boron
    steps:
      - checkout
      - run:
         name: Installing awscli
         command: |
            apt-get -y -qq update
            apt-get -y -qq install awscli
            echo '*****AWS-CLI INSTALLED SUCCESSFULLY*****'
      - run: 
          name: Building the codebase
          command: cd scripts && ./build.sh
      - run: 
          name: Deploying the codebase
          command: ./deploy-to-s3.sh
  build_dev:
    description: our build and deploy job for the website dev environment
    docker:
      - image: node:boron
    steps:
      - checkout
      - run:
         name: Installing awscli
         command: |
            apt-get -y -qq update
            apt-get -y -qq install awscli
            echo '*****AWS-CLI INSTALLED SUCCESSFULLY*****'
      - run: 
          name: Building the codebase
          command: cd scripts && ./build.sh
      - run: 
          name: Deploying the codebase
          command: ./deploy-dev-to-s3.sh
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: staging
      - build_dev:
          filters:
            branches:
              only: dev
