version: 2.1
jobs:
  build:
    description: our build and deploy job for the website dev environment
    docker:
      - image: brentley/awscli
    steps:
      - checkout
      - run: 
          name: Building the codebase
          command: |
            cd scripts 
            sh ./build.sh
  deploy:
    description: Deploying our build to AWS-S3
    docker:
      - image: brentley/awscli
    steps:
      - checkout
      - run: 
          name: Deploying the codebase
          command: |
            cd scripts
            sh ./deploy-to-s3.sh
  deploy_dev:
    description: Deploying our build to AWS-S3
    docker:
      - image: brentley/awscli
    steps:
      - checkout
      - run: 
          name: Deploying the codebase
          command: |
            cd scripts
            sh ./deploy-dev-to-s3.sh
workflows:
  version: 2
  build:
    jobs:
      - build
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: staging
      - deploy_dev:
          filters:
            branches:
              only: dev
