version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.8
jobs:
  build:
    docker:
      - image: 'circleci/python:3.7'
    steps:
      - checkout
      - aws-s3/sync:
          from: ./src
          to: 's3://bart.gariany.com'
          aws-region: AWS_REGION_BLUE
          overwrite: true
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - acceptance_test_1:
          requires:
            - build
      - acceptance_test_2:
          requires:
            - build
      - acceptance_test_3:
          requires:
            - build
      - acceptance_test_4:
          requires:
            - build
      - deploy:
          requires:
            - acceptance_test_1
            - acceptance_test_2
            - acceptance_test_3
            - acceptance_test_4
