version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.9
jobs:
  build:
    description: our build and deploy job for the website
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - checkout
      - run: 
          name: Building the codebase
          command: |
            cd scripts 
            sh ./build.sh
      - aws-s3/sync:
          from: ./public
          to: 's3://bart.gariany.com'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
          overwrite: true
          aws-region: AWS_REGION_BLUE
  build_dev:
    description: our build and deploy job for the website dev environment
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - checkout
      - run: 
          name: Building the codebase
          command: |
            cd scripts 
            sh ./build.sh
      - aws-s3/sync:
          from: ./public
          to: 's3://bart.gariany.com'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
          overwrite: true
          aws-region: AWS_REGION_BLUE
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: staging
      - build_dev:
          filters:
            branches:
              only: dev
